# Site settings
title: Diego Gayou
subtitle: Estudiante Universitario
email: garciagayou@gmail.com
description: |
  Estudio Ciencia de Datos y Matemáticas Aplicadas en el ITAM
  y soy un entusiasta de las cadenas de suministro
baseurl: "" # Empty for user/organization sites
url: https://garcia-gayou.github.io/
author:
  name: Diego Gayou
street_address:
city: Ciudad de México
state:
zip_code: 01049
country: México
phone: +52 55 5334 8082

# Homepage tiles
tiles-source: pages # Accepts "posts" or "pages"
tiles-count: 6

# Social settings
socials:
  GitHub: https://github.com/garcia-gayou
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/diego-garc%C3%ADa-gayou-ruiz-839500221/
  Twitter:
  Facebook:
  Slack:

# Build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
